# Generated by Django 2.0.8 on 2022-04-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='food_item',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='food_item',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
