# Generated by Django 2.0.8 on 2022-04-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220429_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
