# Generated by Django 2.0.8 on 2022-05-01 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChefOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Unavailable')])),
                ('image_url', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OffDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_status', models.IntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'ReadyToServe'), (3, 'Complete'), (-1, 'Cancelled')])),
                ('notes', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('order', models.TimeField()),
                ('delivery_date', models.DateField()),
                ('delivery', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FoodItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Owns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=5)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Complete'), (-1, 'Cancelled')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=10)),
                ('shop_name', models.CharField(max_length=20)),
                ('shop_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('user_role', models.IntegerField(choices=[(0, 'Student'), (1, 'ShopAdmin'), (2, 'Chef')])),
            ],
        ),
        migrations.CreateModel(
            name='WorksFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shop'),
        ),
        migrations.AddField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
        migrations.AddField(
            model_name='owns',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
        migrations.AddField(
            model_name='owns',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
        migrations.AddField(
            model_name='offdays',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shop'),
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shop'),
        ),
        migrations.AddField(
            model_name='cheforders',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
        migrations.AddField(
            model_name='cheforders',
            name='oder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Order'),
        ),
    ]
