# Generated by Django 4.0.4 on 2022-05-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_fooditem_item_id_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
