# Generated by Django 4.0.4 on 2022-05-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_shop_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.FileField(default=0, upload_to='images/fooditems/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(upload_to='images/shops/'),
        ),
    ]
